# Copyright (c) Microsoft. All rights reserved.

from __future__ import annotations

import time
import warnings
from typing import List, Union, Dict

import sglang
from fastapi import Request
from fastapi.responses import ORJSONResponse
from sglang.srt.entrypoints.openai.protocol import ChatCompletionRequest, ChatCompletionResponse, ErrorResponse
from sglang.srt.entrypoints.openai.serving_chat import OpenAIServingChat
from sglang.srt.managers.io_struct import GenerateReqInput

__all__ = [
    "instrument_sglang",
    "uninstrument_sglang",
]


class ChatCompletionResponsePatched(ChatCompletionResponse):
    prompt_messages: List[Dict[str, Any]] | None = None
    prompt_token_ids: List[int] | None = None
    response_token_ids: List[int] | None = None
    response_logprobs: List[Dict[str, float]] | None = None


original_handle_non_streaming_request = OpenAIServingChat._handle_non_streaming_request


async def _handle_non_streaming_request(
    self, adapted_request: GenerateReqInput, request: ChatCompletionRequest,
    raw_request: Request,
) -> Union[ChatCompletionResponse, ErrorResponse, ORJSONResponse]:
    """Handle non-streaming chat completion request"""
    try:
        ret = await self.tokenizer_manager.generate_request(adapted_request, raw_request).__anext__()
    except ValueError as e:
        return self.create_error_response(str(e))

    if not isinstance(ret, list):
        ret = [ret]

    response = self._build_chat_response(request, ret, int(time.time()))

    response_token_ids = [ret_item['output_ids'] for ret_item in ret][0]

    response = response.model_copy(
        update={
            "prompt_messages": request.messages,
            "prompt_token_ids": adapted_request.input_ids,
            "response_token_ids": response_token_ids,
            "response_logprobs": response.choices[0].logprobs.content if response.choices[0].logprobs else None,
        }
    )

    return response


def instrument_sglang():
    """Instrument Sglang to capture token IDs generated by engine."""
    if sglang.srt.entrypoints.openai.protocol.ChatCompletionResponse is ChatCompletionResponsePatched:
        warnings.warn("sglang is already instrumented. Skip the instrumentation.")
        return

    sglang.srt.entrypoints.openai.protocol.ChatCompletionResponse = ChatCompletionResponsePatched
    OpenAIServingChat._handle_non_streaming_request = _handle_non_streaming_request


def uninstrument_sglang():
    """Uninstrument Sglang to stop capturing token IDs generated by engine."""
    OpenAIServingChat._handle_non_streaming_request = original_handle_non_streaming_request
